import './globals.css';

import type { Metadata } from 'next';
import { ReactNode } from 'react';

import Header from '@/components/Header';

export const metadata: Metadata = {
    title: 'StudRada OP',
    description: 'Generated by create next app',
};

const RootLayout = ({
    children,
}: Readonly<{
    children: ReactNode;
}>) => {
    return (
        <html lang='en'>
            <body>
                <Header />
                {children}
            </body>
        </html>
    );
};

export default RootLayout;
